// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import * as dotenv from 'dotenv';
import path, { join } from 'path';
import { defineConfig } from 'prisma/config';
import { getConfig } from './src/common/helpers/get-config.helper';

const envFile = path.resolve(join(__dirname, '/src/config/.env'));
dotenv.config({ path: envFile });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: getConfig('DATABASE_URL'),
  },
});
